version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/app
      - ./_docker/nginx-site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./:/var/www/app

  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - ./:/app
